name: scalecodec
description: 
  Scalecodec library in native dart. Support convertion between object, binary and json.
  Can be used to encode/decode metadata, extrinsics and other substrate related types.

version: 0.1.2
repository: https://github.com/nbltrust/dart-scale-codec

dependencies:
  reflectable: ^4.0.5
  tuple: ^2.0.1
  bs58: ^1.0.2
  cryptography: ^2.4.0

dev_dependencies:
#test_coverage: ^0.5.0
  build_runner: any
  test: any

environment:
  sdk: '>=2.0.0 <3.0.0'
